services:
  # Banco de dados MariaDB
  mariadb:
    image: mariadb:10.8
    container_name: whatsbot-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: bot_db
      MYSQL_USER: bot_user
      MYSQL_PASSWORD: pwd123
    volumes:
      - db_data:/var/lib/mysql
      - ./_dumps:/docker-entrypoint-initdb.d:ro
    ports:
      - "3307:3306"
    networks:
      - skynet 
    command: --default-authentication-plugin=mysql_native_password

  # Servidor Web Apache + PHP
  web:
    build: .
    container_name: webcore
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - skynet 

  # phpMyAdmin (opcional - para gerenciar banco)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: myadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: bot_user
      PMA_PASSWORD: pwd123
    networks:
      - skynet 

volumes:
  db_data:

networks:
  skynet :
    driver: bridge
